### ISSUE TITLE
API server in `master` is not building

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1198]
When I run the [install](https://github.com/hackforla/311-data/blob/master/server/install.sh) script, I get an error when it's building the API server:

```
311-api    | RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
311-api    | Traceback (most recent call last):
311-api    |   File "bin/api_start.py", line 24, in <module>
311-api    |     import app
311-api    |   File "bin/../src/app.py", line 5, in <module>
311-api    |     import control.route_handlers as R
311-api    |   File "bin/../src/control/route_handlers.py", line 5, in <module>
311-api    |     from services import (
311-api    |   File "bin/../src/services/map.py", line 1, in <module>
311-api    |     import pysupercluster
311-api    | ImportError: numpy.core.multiarray failed to import
```
The version of numpy that's in the API's [requirement.txt](https://github.com/hackforla/311-data/blob/master/server/api/requirements.txt#L21) is too old. We should be able to upgrade it and get past this build error.

**Comment by nichhk** [comment]
We're not using the server in `master` anymore, so let's not fix this.
