### ISSUE TITLE
Failing to pull data from Socrata since 6/16

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1258]
@EchoProject noted that the city has changed the 311 request form, changing/adding/deleting different request types, and also adding sub-request types. Designers @melissahermes99 and @elizabeth-ux are concerned about how to represent all of these different request types color-wise.

On the backend, we have been failing to get data from Socrata since 6/16. The dev site says it last pulled data on 6/15. The nightly Prefect tasks are failing, full logs below. It's not immediately obvious from the logs that a change in data schema is causing the nightly Prefect run to fail, but I'll have to investigate more.

- [ ] Determine whether 311 request form change lines up with our nightly Prefect run starting to fail
- [ ] Find out whether 311 data is still being published, and if so, whether the schema has changed

```
[2022-06-18 08:01:49+0000] INFO - prefect \| Starting update flow for 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
--
[2022-06-18 08:01:49+0000] INFO - prefect.FlowRunner \| Beginning Flow run for 'Loading Socrata data to Postgres'
[2022-06-18 08:01:49+0000] INFO - prefect.TaskRunner \| Task 'get_start_datetime': Starting task run...
[2022-06-18 08:01:49+0000] INFO - prefect.TaskRunner \| Task 'datasets': Starting task run...
[2022-06-18 08:01:49+0000] INFO - prefect.TaskRunner \| Task 'datasets': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:49+0000] INFO - prefect.get_start_datetime \| 2022-06-10 08:59:31
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'get_start_datetime': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'download_dataset': Starting task run...
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'download_dataset': Finished task run for task with final state: 'Mapped'
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'prep_load': Starting task run...
[2022-06-18 08:02:49+0000] INFO - prefect.prep_load \| Resetting data
[2022-06-18 08:02:49+0000] INFO - prefect.prep_load \| 'temp_loading' table truncated
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'prep_load': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'load_datafile': Starting task run...
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'load_datafile': Finished task run for task with final state: 'Mapped'
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[0]': Starting task run...
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[1]': Starting task run...
[2022-06-18 08:02:49+0000] INFO - prefect.download_dataset[0] \| Downloading dataset: ms7h-a45h
[2022-06-18 08:02:49+0000] INFO - prefect.download_dataset[1] \| Downloading dataset: ndkd-k878
[2022-06-18 08:02:49+0000] INFO - prefect.download_dataset[0] \| Fetching 100000 rows with offset 0
[2022-06-18 08:02:49+0000] INFO - prefect.download_dataset[1] \| Fetching 100000 rows with offset 0
[2022-06-18 08:02:49+0000] INFO - prefect.download_dataset[0] \| 0 total rows downloaded for dataset: ms7h-a45h
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[0]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:49+0000] INFO - prefect.download_dataset[1] \| 0 total rows downloaded for dataset: ndkd-k878
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[0]': Starting task run...
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[1]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:49+0000] INFO - prefect.load_datafile[0] \| Loading data from file: ms7h-a45h-2022-06-18.csv
[2022-06-18 08:02:49+0000] INFO - prefect.load_datafile[0] \| No file (ms7h-a45h-2022-06-18.csv). Skipping...
[2022-06-18 08:02:49+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[1]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[0]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[1] \| Loading data from file: ndkd-k878-2022-06-18.csv
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[1] \| No file (ndkd-k878-2022-06-18.csv). Skipping...
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[2]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[2] \| Downloading dataset: d4vt-q4t5
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[2] \| Fetching 100000 rows with offset 0
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[1]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[3]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[3] \| Downloading dataset: h65r-yf5i
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[3] \| Fetching 100000 rows with offset 0
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[3] \| 0 total rows downloaded for dataset: h65r-yf5i
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[2] \| 0 total rows downloaded for dataset: d4vt-q4t5
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[3]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[2]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[3]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[2]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[3] \| Loading data from file: h65r-yf5i-2022-06-18.csv
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[3] \| No file (h65r-yf5i-2022-06-18.csv). Skipping...
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[2] \| Loading data from file: d4vt-q4t5-2022-06-18.csv
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[3]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[2] \| No file (d4vt-q4t5-2022-06-18.csv). Skipping...
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[2]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[4]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[4] \| Downloading dataset: pvft-t768
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[4] \| Fetching 100000 rows with offset 0
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[5]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[5] \| Downloading dataset: rq3b-xjk8
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[5] \| Fetching 100000 rows with offset 0
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[4] \| 0 total rows downloaded for dataset: pvft-t768
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[4]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[5] \| 0 total rows downloaded for dataset: rq3b-xjk8
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[4]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[5]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[4] \| Loading data from file: pvft-t768-2022-06-18.csv
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[4] \| No file (pvft-t768-2022-06-18.csv). Skipping...
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[5]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[4]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[5] \| Loading data from file: rq3b-xjk8-2022-06-18.csv
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[6]': Starting task run...
[2022-06-18 08:02:50+0000] INFO - prefect.load_datafile[5] \| No file (rq3b-xjk8-2022-06-18.csv). Skipping...
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[6] \| Downloading dataset: 97z7-y5bt
[2022-06-18 08:02:50+0000] INFO - prefect.download_dataset[6] \| Fetching 100000 rows with offset 0
[2022-06-18 08:02:50+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[5]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[7]': Starting task run...
[2022-06-18 08:02:51+0000] INFO - prefect.download_dataset[7] \| Downloading dataset: i5ke-k6by
[2022-06-18 08:02:51+0000] INFO - prefect.download_dataset[7] \| Fetching 100000 rows with offset 0
[2022-06-18 08:02:51+0000] INFO - prefect.download_dataset[6] \| 0 total rows downloaded for dataset: 97z7-y5bt
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[6]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:51+0000] INFO - prefect.download_dataset[7] \| 0 total rows downloaded for dataset: i5ke-k6by
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'download_dataset[7]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[6]': Starting task run...
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[7]': Starting task run...
[2022-06-18 08:02:51+0000] INFO - prefect.load_datafile[7] \| Loading data from file: i5ke-k6by-2022-06-18.csv
[2022-06-18 08:02:51+0000] INFO - prefect.load_datafile[6] \| Loading data from file: 97z7-y5bt-2022-06-18.csv
[2022-06-18 08:02:51+0000] INFO - prefect.load_datafile[6] \| No file (97z7-y5bt-2022-06-18.csv). Skipping...
[2022-06-18 08:02:51+0000] INFO - prefect.load_datafile[7] \| No file (i5ke-k6by-2022-06-18.csv). Skipping...
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[6]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'load_datafile[7]': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'complete_load': Starting task run...
[2022-06-18 08:02:51+0000] INFO - prefect.complete_load \| Insert/updating 'requests' table with 0 new records
[2022-06-18 08:02:51+0000] INFO - prefect.complete_load \| 0 rows inserted in table 'requests'
[2022-06-18 08:02:51+0000] INFO - prefect.complete_load \| 0 rows updated in table 'requests'
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'complete_load': Finished task run for task with final state: 'Success'
[2022-06-18 08:02:51+0000] INFO - prefect.TaskRunner \| Task 'clear_cache': Starting task run...
[2022-06-18 08:03:14+0000] INFO - prefect.clear_cache \| Cache clearing successful: https://dev-api.311-data.org/status/reset-cache
[2022-06-18 08:03:15+0000] INFO - prefect.TaskRunner \| Task 'clear_cache': Finished task run for task with final state: 'Success'
[2022-06-18 08:03:15+0000] INFO - prefect.TaskRunner \| Task 'reload_reports': Starting task run...
[2022-06-18 08:03:46+0000] ERROR - prefect.TaskRunner \| Unexpected error: TimeoutError('Waiting for selector "#reloading-msg" failed: timeout 30000ms exceeds.')


Traceback (most recent call last):
--
File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
new_state = method(self, state, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 869, in get_task_run_state
logger=self.logger,
File "/usr/local/lib/python3.7/site-packages/prefect/utilities/executors.py", line 299, in run_task_with_timeout
return task.run(*args, **kwargs)  # type: ignore
File "/app/tasks/cache.py", line 71, in reload_reports
result = asyncio.run(run_js_page(reload_path))
File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "/app/tasks/cache.py", line 54, in run_js_page
await page.waitForSelector('#reloading-msg')
File "/usr/local/lib/python3.7/site-packages/pyppeteer/frame_manager.py", line 855, in __await__
raise result
pyppeteer.errors.TimeoutError: Waiting for selector "#reloading-msg" failed: timeout 30000ms exceeds.
[2022-06-18 08:03:46+0000] INFO - prefect.TaskRunner \| Task 'reload_reports': Finished task run for task with final state: 'Failed'
[2022-06-18 08:03:46+0000] INFO - prefect.FlowRunner \| Flow run FAILED: some reference tasks failed.
[2022-06-18 08:03:46+0000] INFO - prefect \| FAILURE: Something went wrong in Loading Socrata data to Postgres: "Some reference tasks failed."
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 152, in _close_process
self._loop.run_until_complete(self.killChrome())
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 562, in run_until_complete
self._check_closed()
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by nichhk** [comment]
This was an interesting error message that I somewhat misinterpreted. In the logs above, it seems like we "successfully" completed the steps to download data from Socrata--it just so happens that there was nothing to download for this particular day. That seems unusual to me, since we typically get >1000 requests a day.

But anyway, it seems like the true error logged above is that we failed to reload the dashboards, which the nightly task performs after retrieving the data. It looks like the reloading is working, based on the dashboard logging:

```
[26/Jun/2022:08:11:54] [2022-06-26 08:11:54 +0000] [9] [WARNING] Report Server reload requested
[26/Jun/2022:08:11:54] [2022-06-26 08:11:54 +0000] [9] [INFO] Worker exiting (pid: 9)
[26/Jun/2022:08:11:55] [2022-06-26 08:11:55 +0000] [11] [INFO] Booting worker with pid: 11
[26/Jun/2022:08:11:57] [2022-06-26 08:11:57 +0000] [11] [INFO] Installing dashboards: neighborhood, neighborhood_recent, overview, recent, types_map
[26/Jun/2022:08:11:57] * Downloading data for dataframe
[26/Jun/2022:08:11:59] * Dataframe has been loaded
[26/Jun/2022:08:12:00] * Downloading data for dataframe
[26/Jun/2022:08:12:04] * Dataframe has been loaded
[26/Jun/2022:08:12:05] * Downloading data for dataframe
[26/Jun/2022:08:12:05] * Downloading data for dataframe
[26/Jun/2022:08:12:05] * Downloading data for dataframe
[26/Jun/2022:08:12:06] * Downloading data for dataframe
[26/Jun/2022:08:12:06] * Downloading data for dataframe
[26/Jun/2022:08:12:07] * Downloading data for dataframe
[26/Jun/2022:08:12:08] * Dataframe has been loaded
[26/Jun/2022:08:12:08] * Downloading data for dataframe
[26/Jun/2022:08:12:37] * Downloading geojson
[26/Jun/2022:08:12:37] [2022-06-26 08:12:37 +0000] [11] [INFO] Report Server ready
[26/Jun/2022:08:12:50] [2022-06-26 08:12:50 +0000] [1] [INFO] Handling signal: term
[26/Jun/2022:08:12:50] [2022-06-26 08:12:50 +0000] [11] [INFO] Worker exiting (pid: 11)
[26/Jun/2022:08:12:51] [2022-06-26 08:12:51 +0000] [1] [INFO] Shutting down: Master
[26/Jun/2022:08:13:27] [2022-06-26 08:13:27 +0000] [1] [INFO] Starting gunicorn 20.0.4
[26/Jun/2022:08:13:27] [2022-06-26 08:13:27 +0000] [1] [INFO] Listening at: http://0.0.0.0:5500 (1)
[26/Jun/2022:08:13:27] [2022-06-26 08:13:27 +0000] [1] [INFO] Using worker: sync
[26/Jun/2022:08:13:27] [2022-06-26 08:13:27 +0000] [9] [INFO] Booting worker with pid: 9
[26/Jun/2022:08:13:29] [2022-06-26 08:13:29 +0000] [9] [INFO] Installing dashboards: neighborhood, neighborhood_recent, overview, recent, types_map
```

It might just be taking a lot longer than the 30000ms timeout, since there are two workers that need to be rebooted. This is another issue to look into, which is not relevant to this particular issue.

Overall, it seems like the change in 311 request form does not affect us (at least yet). We are still able to pull new request data from Socrata.
